public class tryCatchFinally {
    public static void main(String[] args) {
        try{

        }
        catch(ArithmeticException ae ){


        }
    }
}
